# Therapy Bot Development Version
version: "3.8"

services:
  backend:
    image: talking_legislation_backend:latest
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: talking_legislation_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
