# Generated by CodiumAI


class TestReadRoot:

    #  Returns a JSON object with a "message" key and value "Hello, World!"
    def test_returns_json_with_message_key_and_value(self, test_client):
        response = test_client.get("/")
        assert response.status_code == 200
        assert response.json() == {"message": "Hello, World!"}

    #  None
    def test_none(self, test_client):
        response = test_client.get("/")
        assert response.status_code == 200
        assert response.json() == {'message': 'Hello, World!'}

    #  The function should handle concurrent requests without errors
    def test_concurrent_requests(self, test_client):
        # Send multiple concurrent requests to the endpoint
        responses = [test_client.get("/") for _ in range(10)]
        # Check that all responses have a status code of 200
        for response in responses:
            assert response.status_code == 200

    #  The function should return a 404 error for any non-GET requests
    def test_non_get_requests_return_404(self, test_client):
        # Send a POST request to the endpoint
        response = test_client.post("/")
        assert response.status_code == 405

    #  The function should return a 405 error for any non-root path requests
    def test_non_root_path_requests_return_405(self, test_client):
        # Send a GET request to a non-root path
        response = test_client.get("/other")
        assert response.status_code == 404
